<a href="https://colab.research.google.com/github/russamy2010/ClickedAnalytics2024/blob/main/Advanced_SQL_CTE_and_Partition_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read the CSV files into Pandas Dataframes
player_df = pd.read_csv('player.csv')
game_df = pd.read_csv('game.csv')
team_details_df = pd.read_csv('team_details.csv')
common_player_info_df = pd.read_csv('common_player_info.csv')

# Display the first 5 rows of each DataFrame
print("First 5 rows of player_df:")
print(player_df.head().to_markdown(index=False, numalign="left", stralign="left"))

print("\nFirst 5 rows of game_df:")
print(game_df.head().to_markdown(index=False, numalign="left", stralign="left"))

print("\nFirst 5 rows of team_details_df:")
print(team_details_df.head().to_markdown(index=False, numalign="left", stralign="left"))

print("\nFirst 5 rows of common_player_info_df:")
print(common_player_info_df.head().to_markdown(index=False, numalign="left", stralign="left"))

# Print the column names and their data types for each DataFrame
print("\nColumn names and their data types for player_df:")
print(player_df.info())

print("\nColumn names and their data types for game_df:")
print(game_df.info())

print("\nColumn names and their data types for team_details_df:")
print(team_details_df.info())

print("\nColumn names and their data types for common_player_info_df:")
print(common_player_info_df.info())

#Output

```text?code_stdout&code_event_index=2
First 5 rows of player_df:
| id    | full_name           | first_name   | last_name    | is_active   |
|:------|:--------------------|:-------------|:-------------|:------------|
| 76001 | Alaa Abdelnaby      | Alaa         | Abdelnaby    | 0           |
| 76002 | Zaid Abdul-Aziz     | Zaid         | Abdul-Aziz   | 0           |
| 76003 | Kareem Abdul-Jabbar | Kareem       | Abdul-Jabbar | 0           |
| 51    | Mahmoud Abdul-Rauf  | Mahmoud      | Abdul-Rauf   | 0           |
| 1505  | Tariq Abdul-Wahad   | Tariq        | Abdul-Wahad  | 0           |

First 5 rows of game_df:
| season_id   | team_id_home   | team_abbreviation_home   | team_name_home          | game_id   | game_date           | matchup_home   | wl_home   | min   | fgm_home   | fga_home   | fg_pct_home   | fg3m_home   | fg3a_home   | fg3_pct_home   | ftm_home   | fta_home   | ft_pct_home   | oreb_home   | dreb_home   | reb_home   | ast_home   | stl_home   | blk_home   | tov_home   | pf_home   | pts_home   | plus_minus_home   | video_available_home   | team_id_away   | team_abbreviation_away   | team_name_away      | matchup_away   | wl_away   | fgm_away   | fga_away   | fg_pct_away   | fg3m_away   | fg3a_away   | fg3_pct_away   | ftm_away   | fta_away   | ft_pct_away   | oreb_away   | dreb_away   | reb_away   | ast_away   | stl_away   | blk_away   | tov_away   | pf_away   | pts_away   | plus_minus_away   | video_available_away   | season_type    |
|:------------|:---------------|:-------------------------|:------------------------|:----------|:--------------------|:---------------|:----------|:------|:-----------|:-----------|:--------------|:------------|:------------|:---------------|:-----------|:-----------|:--------------|:------------|:------------|:-----------|:-----------|:-----------|:-----------|:-----------|:----------|:-----------|:------------------|:-----------------------|:---------------|:-------------------------|:--------------------|:---------------|:----------|:-----------|:-----------|:--------------|:------------|:------------|:---------------|:-----------|:-----------|:--------------|:------------|:------------|:-----------|:-----------|:-----------|:-----------|:-----------|:----------|:-----------|:------------------|:-----------------------|:---------------|
| 21946       | 1610610035     | HUS                      | Toronto Huskies         | 24600001  | 1946-11-01 00:00:00 | HUS vs. NYK    | L         | 0     | 25         | nan        | nan           | nan         | nan         | nan            | 16         | 29         | 0.552         | nan         | nan         | nan        | nan        | nan        | nan        | nan        | nan       | 66         | -2                | 0                      | 1610612752     | NYK                      | New York Knicks     | NYK @ HUS      | W         | 24         | nan        | nan           | nan         | nan         | nan            | 20         | 26         | 0.769         | nan         | nan         | nan        | nan        | nan        | nan        | nan        | nan       | 68         | 2                 | 0                      | Regular Season |
| 21946       | 1610610034     | BOM                      | St. Louis Bombers       | 24600003  | 1946-11-02 00:00:00 | BOM vs. PIT    | W         | 0     | 20         | 59         | 0.339         | nan         | nan         | nan            | 16         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | 21        | 56         | 5                 | 0                      | 1610610031     | PIT                      | Pittsburgh Ironmen  | PIT @ BOM      | L         | 16         | 72         | 0.222         | nan         | nan         | nan            | 19         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | 25        | 51         | -5                | 0                      | Regular Season |
| 21946       | 1610610032     | PRO                      | Providence Steamrollers | 24600002  | 1946-11-02 00:00:00 | PRO vs. BOS    | W         | 0     | 21         | nan        | nan           | nan         | nan         | nan            | 17         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | nan       | 59         | 6                 | 0                      | 1610612738     | BOS                      | Boston Celtics      | BOS @ PRO      | L         | 21         | nan        | nan           | nan         | nan         | nan            | 11         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | nan       | 53         | -6                | 0                      | Regular Season |
| 21946       | 1610610025     | CHS                      | Chicago Stags           | 24600004  | 1946-11-02 00:00:00 | CHS vs. NYK    | W         | 0     | 21         | nan        | nan           | nan         | nan         | nan            | 21         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | 20        | 63         | 16                | 0                      | 1610612752     | NYK                      | New York Knicks     | NYK @ CHS      | L         | 16         | nan        | nan           | nan         | nan         | nan            | 15         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | 22        | 47         | -16               | 0                      | Regular Season |
| 21946       | 1610610028     | DEF                      | Detroit Falcons         | 24600005  | 1946-11-02 00:00:00 | DEF vs. WAS    | L         | 0     | 10         | nan        | nan           | nan         | nan         | nan            | 13         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | nan       | 33         | -17               | 0                      | 1610610036     | WAS                      | Washington Capitols | WAS @ DEF      | W         | 18         | nan        | nan           | nan         | nan         | nan            | 14         | nan        | nan           | nan         | nan         | nan        | nan        | nan        | nan        | nan        | nan       | 50         | 17                | 0                      | Regular Season |

First 5 rows of team_details_df:
| team_id    | abbreviation   | nickname   | yearfounded   | city         | arena                    | arenacapacity   | owner             | generalmanager     | headcoach      | dleagueaffiliation    | facebook                               | instagram                          | twitter                          |
|:-----------|:---------------|:-----------|:--------------|:-------------|:-------------------------|:----------------|:------------------|:-------------------|:---------------|:----------------------|:---------------------------------------|:-----------------------------------|:---------------------------------|
| 1610612737 | ATL            | Hawks      | 1949          | Atlanta      | State Farm Arena         | 18729           | Tony Ressler      | Travis Schlenk     | Quin Snyder    | College Park Skyhawks | https://www.facebook.com/hawks         | https://instagram.com/atlhawks     | https://twitter.com/ATLHawks     |
| 1610612741 | CHI            | Bulls      | 1966          | Chicago      | United Center            | 21711           | Michael Reinsdorf | Arturas Karnisovas | Billy Donovan  | Windy City Bulls      | https://www.facebook.com/chicagobulls  | https://instagram.com/chicagobulls | https://twitter.com/chicagobulls |
| 1610612742 | DAL            | Mavericks  | 1980          | Dallas       | American Airlines Center | 19200           | Mark Cuban        | Nico Harrison      | Jason Kidd     | Texas Legends         | https://www.facebook.com/dallasmavs    | https://instagram.com/dallasmavs   | https://twitter.com/dallasmavs   |
| 1610612743 | DEN            | Nuggets    | 1976          | Denver       | Ball Arena               | nan             | Stan Kroenke      | Calvin Booth       | Michael Malone | Grand Rapids Gold     | https://www.facebook.com/DenverNuggets | https://instagram.com/nuggets      | https://twitter.com/nuggets      |
| 1610612744 | GSW            | Warriors   | 1946          | Golden State | Chase Center             | nan             | Joe Lacob         | Bob Myers          | Steve Kerr     | Santa Cruz Warriors   | https://www.facebook.com/warriors      | https://instagram.com/warriors     | https://twitter.com/warriors     |

First 5 rows of common_player_info_df:
| person_id   | first_name   | last_name    | display_first_last   | display_last_comma_first   | display_fi_last   | player_slug         | birthdate           | school         | country   | last_affiliation      | height   | weight   | season_exp   | jersey   | position      | rosterstatus   | games_played_current_season_flag   | team_id    | team_name     | team_abbreviation   | team_code   | team_city    | playercode                  | from_year   | to_year   | dleague_flag   | nba_flag   | games_played_flag   | draft_year   | draft_round   | draft_number   | greatest_75_flag   |
|:------------|:-------------|:-------------|:---------------------|:---------------------------|:------------------|:--------------------|:--------------------|:---------------|:----------|:----------------------|:---------|:---------|:-------------|:---------|:--------------|:---------------|:-----------------------------------|:-----------|:--------------|:--------------------|:------------|:-------------|:----------------------------|:------------|:----------|:---------------|:-----------|:--------------------|:-------------|:--------------|:---------------|:-------------------|
| 76001       | Alaa         | Abdelnaby    | Alaa Abdelnaby       | Abdelnaby, Alaa            | A. Abdelnaby      | alaa-abdelnaby      | 1968-06-24 00:00:00 | Duke           | USA       | Duke/USA              | 6-10     | 240      | 5            | 30       | Forward       | Inactive       | N                                  | 1610612757 | Trail Blazers | POR                 | blazers     | Portland     | HISTADD_alaa_abdelnaby      | 1990        | 1994      | N              | Y          | Y                   | 1990         | 1             | 25             | N                  |
| 76003       | Kareem       | Abdul-Jabbar | Kareem Abdul-Jabbar  | Abdul-Jabbar, Kareem       | K. Abdul-Jabbar   | kareem-abdul-jabbar | 1947-04-16 00:00:00 | UCLA           | USA       | UCLA/USA              | 7-2      | 225      | 20           | 33       | Center        | Inactive       | N                                  | 1610612747 | Lakers        | LAL                 | lakers      | Los Angeles  | HISTADD_kareem_abdul-jabbar | 1969        | 1988      | N              | Y          | Y                   | 1969         | 1             | 1              | Y                  |
| 1505        | Tariq        | Abdul-Wahad  | Tariq Abdul-Wahad    | Abdul-Wahad, Tariq         | T. Abdul-Wahad    | tariq-abdul-wahad   | 1974-11-03 00:00:00 | San Jose State | France    | San Jose State/France | 6-6      | 235      | 7            | 9        | Forward-Guard | Inactive       | N                                  | 1610612758 | Kings         | SAC                 | kings       | Sacramento   | tariq_abdul-wahad           | 1997        | 2003      | N              | Y          | Y                   | 1997         | 1             | 11             | N                  |
| 949         | Shareef      | Abdur-Rahim  | Shareef Abdur-Rahim  | Abdur-Rahim, Shareef       | S. Abdur-Rahim    | shareef-abdur-rahim | 1976-12-11 00:00:00 | California     | USA       | California/USA        | 6-9      | 245      | 13           | 3        | Forward       | Inactive       | N                                  | 1610612763 | Grizzlies     | VAN                 | grizzlies   | Vancouver    | shareef_abdur-rahim         | 1996        | 2007      | N              | Y          | Y                   | 1996         | 1             | 3              | N                  |
| 76005       | Tom          | Abernethy    | Tom Abernethy        | Abernethy, Tom             | T. Abernethy      | tom-abernethy       | 1954-05-06 00:00:00 | Indiana        | USA       | Indiana/USA           | 6-7      | 220      | 5            | 5        | Forward       | Inactive       | N                                  | 1610612744 | Warriors      | GOS                 | warriors    | Golden State | HISTADD_tom_abernethy       | 1976        | 1980      | N              | Y          | Y                   | 1976         | 3             | 43             | N                  |

Column names and their data types for player_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4831 entries, 0 to 4830
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4831 non-null   int64
 1   full_name   4831 non-null   object
 2   first_name  4825 non-null   object
 3   last_name   4831 non-null   object
 4   is_active   4831 non-null   int64
dtypes: int64(2), object(3)
memory usage: 188.8+ KB
None

Column names and their data types for game_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65698 entries, 0 to 65697
Data columns (total 55 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   season_id               65698 non-null  int64  
 1   team_id_home            65698 non-null  int64  
 2   team_abbreviation_home  65698 non-null  object
 3   team_name_home          65698 non-null  object
 4   game_id                 65698 non-null  int64  
 5   game_date               65698 non-null  object
 6   matchup_home            65698 non-null  object
 7   wl_home                 65696 non-null  object
 8   min                     65698 non-null  int64  
 9   fgm_home                65685 non-null  float64
 10  fga_home                50251 non-null  float64
 11  fg_pct_home             50208 non-null  float64
 12  fg3m_home               52480 non-null  float64
 13  fg3a_home               47015 non-null  float64
 14  fg3_pct_home            46624 non-null  float64
 15  ftm_home                65682 non-null  float64
 16  fta_home                62694 non-null  float64
 17  ft_pct_home             62689 non-null  float64
 18  oreb_home               46762 non-null  float64
 19  dreb_home               46699 non-null  float64
 20  reb_home                49969 non-null  float64
 21  ast_home                49893 non-null  float64
 22  stl_home                46849 non-null  float64
 23  blk_home                47072 non-null  float64
 24  tov_home                47014 non-null  float64
 25  pf_home                 62842 non-null  float64
 26  pts_home                65698 non-null  float64
 27  plus_minus_home         65698 non-null  int64  
 28  video_available_home    65698 non-null  int64  
 29  team_id_away            65698 non-null  int64  
 30  team_abbreviation_away  65698 non-null  object
 31  team_name_away          65698 non-null  object
 32  matchup_away            65698 non-null  object
 33  wl_away                 65696 non-null  object
 34  fgm_away                65685 non-null  float64
 35  fga_away                50251 non-null  float64
 36  fg_pct_away             50209 non-null  float64
 37  fg3m_away               52480 non-null  float64
 38  fg3a_away               47015 non-null  float64
 39  fg3_pct_away            46736 non-null  float64
 40  ftm_away                65685 non-null  float64
 41  fta_away                62694 non-null  float64
 42  ft_pct_away             62692 non-null  float64
 43  oreb_away               46762 non-null  float64
 44  dreb_away               46700 non-null  float64
 45  reb_away                49973 non-null  float64
 46  ast_away                49897 non-null  float64
 47  stl_away                46849 non-null  float64
 48  blk_away                47073 non-null  float64
 49  tov_away                47013 non-null  float64
 50  pf_away                 62847 non-null  float64
 51  pts_away                65698 non-null  float64
 52  plus_minus_away         65698 non-null  int64  
 53  video_available_away    65698 non-null  int64  
 54  season_type             65698 non-null  object
dtypes: float64(36), int64(9), object(10)
memory usage: 27.6+ MB
None

Column names and their data types for team_details_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   team_id             25 non-null     int64  
 1   abbreviation        25 non-null     object
 2   nickname            25 non-null     object
 3   yearfounded         25 non-null     float64
 4   city                25 non-null     object
 5   arena               25 non-null     object
 6   arenacapacity       16 non-null     float64
 7   owner               25 non-null     object
 8   generalmanager      25 non-null     object
 9   headcoach           24 non-null     object
 10  dleagueaffiliation  25 non-null     object
 11  facebook            25 non-null     object
 12  instagram           25 non-null     object
 13  twitter             25 non-null     object
dtypes: float64(2), int64(1), object(11)
memory usage: 2.9+ KB
None

Column names and their data types for common_player_info_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4171 entries, 0 to 4170
Data columns (total 33 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   person_id                         4171 non-null   int64  
 1   first_name                        4171 non-null   object
 2   last_name                         4171 non-null   object
 3   display_first_last                4171 non-null   object
 4   display_last_comma_first          4171 non-null   object
 5   display_fi_last                   4171 non-null   object
 6   player_slug                       4171 non-null   object
 7   birthdate                         4171 non-null   object
 8   school                            4156 non-null   object
 9   country                           4170 non-null   object
 10  last_affiliation                  4171 non-null   object
 11  height                            4075 non-null   object
 12  weight                            4071 non-null   float64
 13  season_exp                        4171 non-null   float64
 14  jersey                            3191 non-null   object
 15  position                          4108 non-null   object
 16  rosterstatus                      4171 non-null   object
 17  games_played_current_season_flag  4171 non-null   object
 18  team_id                           4171 non-null   int64  
 19  team_name                         3469 non-null   object
 20  team_abbreviation                 3469 non-null   object
 21  team_code                         3469 non-null   object
 22  team_city                         3469 non-null   object
 23  playercode                        4170 non-null   object
 24  from_year                         4156 non-null   float64
 25  to_year                           4156 non-null   float64
 26  dleague_flag                      4171 non-null   object
 27  nba_flag                          4171 non-null   object
 28  games_played_flag                 4171 non-null   object
 29  draft_year                        4171 non-null   object
 30  draft_round                       4007 non-null   object
 31  draft_number                      3948 non-null   object
 32  greatest_75_flag                  4171 non-null   object
dtypes: float64(4), int64(2), object(27)
memory usage: 1.1+ MB
None

```
The `game_df` table contains game-level data, including the home and away teams, various game statistics, and the season type. We can use this table to create a CTE that calculates the average points scored by the home team for each season and season type combination.

In [ ]:
from pandas import DataFrame

# Filter the game_df to only include rows where season_type is 'Regular Season'
regular_season_df = game_df[game_df['season_type'] == 'Regular Season'].copy()

# Group the filtered DataFrame by `season_id` and `season_type` and calculate the mean of `pts_home`
avg_home_points_by_season_df: DataFrame = regular_season_df.groupby(['season_id', 'season_type'])['pts_home'].mean().reset_index()

# Rename `pts_home` column to `avg_pts_home`
avg_home_points_by_season_df = avg_home_points_by_season_df.rename(columns={'pts_home': 'avg_pts_home'})

# Create a CTE called `avg_home_points_by_season` using this new dataframe
with pd.option_context("display.max_rows", None, "display.max_columns", None):
  avg_home_points_by_season = avg_home_points_by_season_df.assign(
      avg_pts_home=lambda x: x["avg_pts_home"].round(2)
  )
  cte_query = f"""
  WITH avg_home_points_by_season AS (
    {avg_home_points_by_season.to_markdown(index=False, numalign="left", stralign="left")}
  )
  SELECT *
  FROM avg_home_points_by_season
  """

  # Display the CTE
  print(cte_query)

#Output
```text?code_stdout&code_event_index=6

  WITH avg_home_points_by_season AS (
    | season_id   | season_type    | avg_pts_home   |
|:------------|:---------------|:---------------|
| 21946       | Regular Season | 69             |
| 21947       | Regular Season | 73.54          |
| 21948       | Regular Season | 81.89          |
| 21949       | Regular Season | 83.11          |
| 21950       | Regular Season | 87.48          |
| 21951       | Regular Season | 86.86          |
| 21952       | Regular Season | 85.22          |
| 21953       | Regular Season | 82.46          |
| 21954       | Regular Season | 95.73          |
| 21955       | Regular Season | 101.43         |
| 21956       | Regular Season | 102.8          |
| 21957       | Regular Season | 109.5          |
| 21958       | Regular Season | 111.07         |
| 21959       | Regular Season | 118.05         |
| 21962       | Regular Season | 117.75         |
| 21963       | Regular Season | 113.28         |
| 21964       | Regular Season | 112.76         |
| 21965       | Regular Season | 118.64         |
| 21967       | Regular Season | 117.99         |
| 21968       | Regular Season | 113.77         |
| 21969       | Regular Season | 118.28         |
| 21971       | Regular Season | 111.9          |
| 21972       | Regular Season | 109.28         |
| 21973       | Regular Season | 107.69         |
| 21974       | Regular Season | 104.55         |
| 21977       | Regular Season | 110.78         |
| 21978       | Regular Season | 112.84         |
| 21979       | Regular Season | 111.4          |
| 21980       | Regular Season | 110.03         |
| 21981       | Regular Season | 110.41         |
| 21982       | Regular Season | 110.36         |
| 21983       | Regular Season | 112.5          |
| 21984       | Regular Season | 112.67         |
| 21985       | Regular Season | 112.49         |
| 21986       | Regular Season | 112.52         |
| 21987       | Regular Season | 111.08         |
| 21988       | Regular Season | 111.97         |
| 21989       | Regular Season | 109.5          |
| 21990       | Regular Season | 108.67         |
| 21991       | Regular Season | 107.54         |
| 21992       | Regular Season | 107.28         |
| 21993       | Regular Season | 103.52         |
| 21994       | Regular Season | 102.99         |
| 21995       | Regular Season | 101.12         |
| 21996       | Regular Season | 98.19          |
| 21997       | Regular Season | 97.04          |
| 21998       | Regular Season | 93.3           |
| 21999       | Regular Season | 99.24          |
| 22000       | Regular Season | 96.27          |
| 22001       | Regular Season | 97.18          |
| 22002       | Regular Season | 97.02          |
| 22003       | Regular Season | 95.2           |
| 22004       | Regular Season | 98.76          |
| 22005       | Regular Season | 98.69          |
| 22006       | Regular Season | 100.23         |
| 22007       | Regular Season | 101.63         |
| 22008       | Regular Season | 101.58         |
| 22009       | Regular Season | 101.81         |
| 22010       | Regular Season | 101.13         |
| 22011       | Regular Season | 97.67          |
| 22013       | Regular Season | 102.31         |
| 22014       | Regular Season | 101.22         |
| 22015       | Regular Season | 104.01         |
| 22016       | Regular Season | 107.17         |
| 22017       | Regular Season | 107.39         |
| 22018       | Regular Season | 112.57         |
| 22019       | Regular Season | 112.86         |
| 22020       | Regular Season | 112.56         |
| 22021       | Regular Season | 111.48         |
| 22022       | Regular Season | 115.94         |
  )
  SELECT *
  FROM avg_home_points_by_season
  

```
Output:

```
  WITH avg_home_points_by_season AS (
    | season_id   | season_type    | avg_pts_home   |
|:------------|:---------------|:---------------|
| 21946       | Regular Season | 69             |
| 21947       | Regular Season | 73.54          |
| 21948       | Regular Season | 81.89          |
| 21949       | Regular Season | 83.11          |
| 21950       | Regular Season | 87.48          |
| 21951       | Regular Season | 86.86          |
| 21952       | Regular Season | 85.22          |
| 21953       | Regular Season | 82.46          |
| 21954       | Regular Season | 95.73          |
| 21955       | Regular Season | 101.43         |
| 21956       | Regular Season | 102.8          |
| 21957       | Regular Season | 109.5          |
| 21958       | Regular Season | 111.07         |
| 21959       | Regular Season | 118.05         |
| 21962       | Regular Season | 117.75         |
| 21963       | Regular Season | 113.28         |
| 21964       | Regular Season | 112.76         |
| 21965       | Regular Season | 118.64         |
| 21967       | Regular Season | 117.99         |
| 21968       | Regular Season | 113.77         |
| 21969       | Regular Season | 118.28         |
| 21971       | Regular Season | 111.9          |
| 21972       | Regular Season | 109.28         |
| 21973       | Regular Season | 107.69         |
| 21974       | Regular Season | 104.55         |
| 21977       | Regular Season | 110.78         |
| 21978       | Regular Season | 112.84         |
| 21979       | Regular Season | 111.4          |
| 21980       | Regular Season | 110.03         |
| 21981       | Regular Season | 110.41         |
| 21982       | Regular Season | 110.36         |
| 21983       | Regular Season | 112.5          |
| 21984       | Regular Season | 112.67         |
| 21985       | Regular Season | 112.49         |
| 21986       | Regular Season | 112.52         |
| 21987       | Regular Season | 111.08         |
| 21988       | Regular Season | 111.97         |
| 21989       | Regular Season | 109.5          |
| 21990       | Regular Season | 108.67         |
| 21991       | Regular Season | 107.54         |
| 21992       | Regular Season | 107.28         |
| 21993       | Regular Season | 103.52         |
| 21994       | Regular Season | 102.99         |
| 21995       | Regular Season | 101.12         |
| 21996       | Regular Season | 98.19          |
| 21997       | Regular Season | 97.04          |
| 21998       | Regular Season | 93.3           |
| 21999       | Regular Season | 99.24          |
| 22000       | Regular Season | 96.27          |
| 22001       | Regular Season | 97.18          |
| 22002       | Regular Season | 97.02          |
| 22003       | Regular Season | 95.2           |
| 22004       | Regular Season | 98.76          |
| 22005       | Regular Season | 98.69          |
| 22006       | Regular Season | 100.23         |
| 22007       | Regular Season | 101.63         |
| 22008       | Regular Season | 101.58         |
| 22009       | Regular Season | 101.81         |
| 22010       | Regular Season | 101.13         |
| 22011       | Regular Season | 97.67          |
| 22013       | Regular Season | 102.31         |
| 22014       | Regular Season | 101.22         |
| 22015       | Regular Season | 104.01         |
| 22016       | Regular Season | 107.17         |
| 22017       | Regular Season | 107.39         |
| 22018       | Regular Season | 112.57         |
| 22019       | Regular Season | 112.86         |
| 22020       | Regular Season | 112.56         |
| 22021       | Regular Season | 111.48         |
| 22022       | Regular Season | 115.94         |
  )
  SELECT *
  FROM avg_home_points_by_season
  
```

This CTE, named `avg_home_points_by_season`, calculates the average points scored by the home team in each season, considering only 'Regular Season' games. The result is a table with columns `season_id`, `season_type`, and `avg_pts_home`.

**Key points about CTEs:**

* **Readability:** They make complex queries easier to understand and manage by breaking them down into smaller, logical steps.
* **Reusability:** A CTE can be referenced multiple times within the same query, promoting code reusability and efficiency.
* **Temporary:** CTEs exist only for the duration of the query and are not stored as permanent database objects.

In [ ]:
# @title Horizontal Partitioning

 """
    Use horizontal partitioning on 'game.df' to create two separate tables: one for home team statistics and one for away team statistics.
    This can improve query performance by reducing the amount of data that needs to be scanned for queries
    that only need data from one of the two teams.

    :pd.option_context: Context manager to temporarily set options in the with statement context.
    :lambda: lambda function in Python Pandas is a small anonymous function primarily used for quick data manipulation within the Pandas library. These anonymous
    or inline functions offer a compact way to perform operations on DataFrames and Series without any formal function declaration.
    """

    """
  Strategy :
     1) Select the required columns from `game_df` and rename them for home team stats
     2) Select the required columns from `game_df` and rename them for away team stats
     3) Create CTEs for home and away team stats
     4) Display the CTEs and the combined query
    """

# Select the required columns from `game_df` and rename them for home team stats
home_team_stats_df = game_df[[
    'season_id', 'team_id_home', 'team_abbreviation_home', 'team_name_home', 'game_id', 'game_date', 'matchup_home', 'wl_home',
    'fgm_home', 'fga_home', 'fg_pct_home', 'fg3m_home', 'fg3a_home', 'fg3_pct_home', 'ftm_home', 'fta_home', 'ft_pct_home',
    'oreb_home', 'dreb_home', 'reb_home', 'ast_home', 'stl_home', 'blk_home', 'tov_home', 'pf_home', 'pts_home', 'plus_minus_home'
]].rename(columns={
    'team_id_home': 'team_id',
    'team_abbreviation_home': 'team_abbreviation',
    'team_name_home': 'team_name',
    'matchup_home': 'matchup',
    'wl_home': 'wl',
    'fgm_home': 'fgm',
    'fga_home': 'fga',
    'fg_pct_home': 'fg_pct',
    'fg3m_home': 'fg3m',
    'fg3a_home': 'fg3a',
    'fg3_pct_home': 'fg3_pct',
    'ftm_home': 'ftm',
    'fta_home': 'fta',
    'ft_pct_home': 'ft_pct',
    'oreb_home': 'oreb',
    'dreb_home': 'dreb',
    'reb_home': 'reb',
    'ast_home': 'ast',
    'stl_home': 'stl',
    'blk_home': 'blk',
    'tov_home': 'tov',
    'pf_home': 'pf',
    'pts_home': 'pts',
    'plus_minus_home': 'plus_minus'
})

# Select the required columns from `game_df` and rename them for away team stats
away_team_stats_df = game_df[[
    'season_id', 'team_id_away', 'team_abbreviation_away', 'team_name_away', 'game_id', 'game_date', 'matchup_away', 'wl_away',
    'fgm_away', 'fga_away', 'fg_pct_away', 'fg3m_away', 'fg3a_away', 'fg3_pct_away', 'ftm_away', 'fta_away', 'ft_pct_away',
    'oreb_away', 'dreb_away', 'reb_away', 'ast_away', 'stl_away', 'blk_away', 'tov_away', 'pf_away', 'pts_away', 'plus_minus_away'
]].rename(columns={
    'team_id_away': 'team_id',
    'team_abbreviation_away': 'team_abbreviation',
    'team_name_away': 'team_name',
    'matchup_away': 'matchup',
    'wl_away': 'wl',
    'fgm_away': 'fgm',
    'fga_away': 'fga',
    'fg_pct_away': 'fg_pct',
    'fg3m_away': 'fg3m',
    'fg3a_away': 'fg3a',
    'fg3_pct_away': 'fg3_pct',
    'ftm_away': 'ftm',
    'fta_away': 'fta',
    'ft_pct_away': 'ft_pct',
    'oreb_away': 'oreb',
    'dreb_away': 'dreb',
    'reb_away': 'reb',
    'ast_away': 'ast',
    'stl_away': 'stl',
    'blk_away': 'blk',
    'tov_away': 'tov',
    'pf_away': 'pf',
    'pts_away': 'pts',
    'plus_minus_away': 'plus_minus'
})

# Create CTEs for home and away team stats
with pd.option_context("display.max_rows", None, "display.max_columns", None):
  home_team_stats = home_team_stats_df
  away_team_stats = away_team_stats_df

  cte_query = f"""
  WITH home_team_stats AS (
    {home_team_stats.to_markdown(index=False, numalign="left", stralign="left")}
  ),
  away_team_stats AS (
    {away_team_stats.to_markdown(index=False, numalign="left", stralign="left")}
  )
  SELECT *
  FROM home_team_stats
  UNION ALL
  SELECT *
  FROM away_team_stats
  """

  # Display the CTEs and the combined query
  print(cte_query)

Output
```text?code_stdout&code_event_index=3

  WITH home_team_stats AS (
    | season_id   | team_id    | team_abbreviation   | team_name                         | game_id   | game_date           | matchup     | wl   | fgm   | fga   | fg_pct   | fg3m   | fg3a   | fg3_pct   | ftm   | fta   | ft_pct   | oreb   | dreb   | reb   | ast   | stl   | blk   | tov   | pf   | pts   | plus_minus   |
|:------------|:-----------|:--------------------|:----------------------------------|:----------|:--------------------|:------------|:-----|:------|:------|:---------|:-------|:-------|:----------|:------|:------|:---------|:-------|:-------|:------|:------|:------|:------|:------|:-----|:------|:-------------|
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600001  | 1946-11-01 00:00:00 | HUS vs. NYK | L    | 25    | nan   | nan      | nan    | nan    | nan       | 16    | 29    | 0.552    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 66    | -2           |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600003  | 1946-11-02 00:00:00 | BOM vs. PIT | W    | 20    | 59    | 0.339    | nan    | nan    | nan       | 16    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 56    | 5            |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600002  | 1946-11-02 00:00:00 | PRO vs. BOS | W    | 21    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 59    | 6            |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600004  | 1946-11-02 00:00:00 | CHS vs. NYK | W    | 21    | nan   | nan      | nan    | nan    | nan       | 21    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 63    | 16           |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600005  | 1946-11-02 00:00:00 | DEF vs. WAS | L    | 10    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 33    | -17          |
| 21946       | 1610610026 | CLR                 | Cleveland Rebels                  | 24600006  | 1946-11-03 00:00:00 | CLR vs. HUS | W    | 24    | nan   | nan      | nan    | nan    | nan       | 23    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 71    | 11           |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600007  | 1946-11-04 00:00:00 | PIT vs. WAS | L    | 19    | nan   | nan      | nan    | nan    | nan       | 18    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 56    | -15          |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600008  | 1946-11-05 00:00:00 | BOS vs. CHS | L    | 23    | nan   | nan      | nan    | nan    | nan       | 9     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 55    | -2           |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600009  | 1946-11-05 00:00:00 | DEF vs. BOM | L    | 18    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 49    | -4           |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600011  | 1946-11-07 00:00:00 | PRO vs. CHS | W    | 31    | nan   | nan      | nan    | nan    | nan       | 11    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 73    | 8            |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600012  | 1946-11-07 00:00:00 | BOM vs. NYK | L    | 25    | 104   | 0.24     | nan    | nan    | nan       | 13    | 20    | 0.65     | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 63    | -5           |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600010  | 1946-11-07 00:00:00 | PHW vs. PIT | W    | 28    | nan   | nan      | nan    | nan    | nan       | 25    | 39    | 0.641    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 24   | 81    | 6            |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600013  | 1946-11-08 00:00:00 | HUS vs. DEF | W    | 31    | nan   | nan      | nan    | nan    | nan       | 11    | 26    | 0.423    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 73    | 2            |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600014  | 1946-11-09 00:00:00 | BOM vs. WAS | W    | 28    | nan   | nan      | nan    | nan    | nan       | 14    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 36   | 70    | 1            |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600015  | 1946-11-09 00:00:00 | PRO vs. PIT | W    | 22    | nan   | nan      | nan    | nan    | nan       | 32    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 76    | 10           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600016  | 1946-11-09 00:00:00 | CHS vs. HUS | W    | 22    | nan   | nan      | nan    | nan    | nan       | 18    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 22   | 64    | 10           |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600017  | 1946-11-09 00:00:00 | DEF vs. BOS | W    | 26    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 69    | 23           |
| 21946       | 1610610026 | CLR                 | Cleveland Rebels                  | 24600018  | 1946-11-10 00:00:00 | CLR vs. WAS | W    | 42    | nan   | nan      | nan    | nan    | nan       | 8     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 92    | 24           |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600020  | 1946-11-11 00:00:00 | NYK vs. CHS | L    | 26    | nan   | nan      | nan    | nan    | nan       | 16    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 25   | 68    | -10          |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600019  | 1946-11-11 00:00:00 | PIT vs. PRO | W    | 29    | nan   | nan      | nan    | nan    | nan       | 26    | 35    | 0.743    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 32   | 84    | 13           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600022  | 1946-11-13 00:00:00 | CHS vs. BOS | W    | 29    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 71    | 10           |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600021  | 1946-11-13 00:00:00 | DEF vs. PRO | L    | 24    | nan   | nan      | nan    | nan    | nan       | 20    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 68    | -2           |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600024  | 1946-11-14 00:00:00 | BOM vs. BOS | W    | 29    | nan   | nan      | nan    | nan    | nan       | 6     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 64    | 2            |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600023  | 1946-11-14 00:00:00 | PHW vs. WAS | W    | 26    | nan   | nan      | nan    | nan    | nan       | 16    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 68    | 3            |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600025  | 1946-11-15 00:00:00 | HUS vs. PRO | W    | 32    | nan   | nan      | nan    | nan    | nan       | 21    | 28    | 0.75     | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 22   | 85    | 17           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600027  | 1946-11-16 00:00:00 | CHS vs. WAS | L    | 21    | nan   | nan      | nan    | nan    | nan       | 23    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 24   | 65    | -8           |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600029  | 1946-11-16 00:00:00 | PRO vs. DEF | L    | 21    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 59    | -11          |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600030  | 1946-11-16 00:00:00 | BOS vs. HUS | W    | 18    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 53    | 4            |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600026  | 1946-11-16 00:00:00 | BOM vs. CLR | W    | 35    | 120   | 0.292    | nan    | nan    | nan       | 13    | 22    | 0.591    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 83    | 9            |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600028  | 1946-11-16 00:00:00 | NYK vs. PIT | W    | 23    | nan   | nan      | nan    | nan    | nan       | 18    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 64    | 2            |
| 21946       | 1610610026 | CLR                 | Cleveland Rebels                  | 24600031  | 1946-11-17 00:00:00 | CLR vs. CHS | L    | 32    | nan   | nan      | nan    | nan    | nan       | 12    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 76    | -2           |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600032  | 1946-11-18 00:00:00 | NYK vs. DEF | W    | 25    | nan   | nan      | nan    | nan    | nan       | 11    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 61    | 4            |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600033  | 1946-11-18 00:00:00 | PIT vs. HUS | W    | 23    | nan   | nan      | nan    | nan    | nan       | 8     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 54    | 6            |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600034  | 1946-11-19 00:00:00 | HUS vs. CLR | L    | 29    | nan   | nan      | nan    | nan    | nan       | 14    | 21    | 0.667    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 18   | 72    | -2           |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600035  | 1946-11-19 00:00:00 | PHW vs. BOM | L    | 25    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 17   | 63    | -3           |
| 21946       | 1610610036 | WAS                 | Washington Capitols               | 24600038  | 1946-11-20 00:00:00 | WAS vs. BOM | W    | 23    | nan   | nan      | nan    | nan    | nan       | 8     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 54    | 3            |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600037  | 1946-11-20 00:00:00 | DEF vs. PIT | L    | 22    | nan   | nan      | nan    | nan    | nan       | 9     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 53    | -1           |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600036  | 1946-11-20 00:00:00 | NYK vs. CHS | W    | 26    | nan   | nan      | nan    | nan    | nan       | 20    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 18   | 72    | 3            |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600041  | 1946-11-21 00:00:00 | BOS vs. BOM | L    | 22    | nan   | nan      | nan    | nan    | nan       | 9     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 11   | 53    | -12          |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600039  | 1946-11-21 00:00:00 | PHW vs. CHS | L    | 23    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 12   | 63    | -2           |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600040  | 1946-11-21 00:00:00 | PRO vs. WAS | L    | 22    | nan   | nan      | nan    | nan    | nan       | 14    | 20    | 0.7      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 19   | 58    | -8           |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600042  | 1946-11-22 00:00:00 | HUS vs. BOS | W    | 26    | nan   | nan      | nan    | nan    | nan       | 31    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 83    | 1            |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600046  | 1946-11-23 00:00:00 | DEF vs. BOS | W    | 22    | nan   | nan      | nan    | nan    | nan       | 10    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 54    | 8            |
| 21946       | 1610610036 | WAS                 | Washington Capitols               | 24600045  | 1946-11-23 00:00:00 | WAS vs. HUS | W    | 27    | nan   | nan      | nan    | nan    | nan       | 20    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 74    | 24           |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600043  | 1946-11-23 00:00:00 | NYK vs. CLR | W    | 34    | nan   | nan      | nan    | nan    | nan       | 14    | 29    | 0.483    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 82    | 6            |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600044  | 1946-11-23 00:00:00 | PRO vs. BOM | L    | 22    | nan   | nan      | nan    | nan    | nan       | 15    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 15   | 59    | -6           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600048  | 1946-11-24 00:00:00 | CHS vs. DEF | L    | 18    | nan   | nan      | nan    | nan    | nan       | 19    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 23   | 55    | -13          |
| 21946       | 1610610026 | CLR                 | Cleveland Rebels                  | 24600047  | 1946-11-24 00:00:00 | CLR vs. PIT | W    | 27    | nan   | nan      | nan    | nan    | nan       | 8     | 20    | 0.4      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 18   | 62    | 2            |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600049  | 1946-11-25 00:00:00 | BOS vs. PRO | L    | 24    | nan   | nan      | nan    | nan    | nan       | 11    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 59    | -12          |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600050  | 1946-11-25 00:00:00 | PIT vs. NYK | L    | 16    | nan   | nan      | nan    | nan    | nan       | 14    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 46    | -16          |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600053  | 1946-11-26 00:00:00 | DEF vs. CLR | W    | 27    | nan   | nan      | nan    | nan    | nan       | 12    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 66    | 20           |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600052  | 1946-11-26 00:00:00 | PHW vs. BOS | W    | 26    | nan   | nan      | nan    | nan    | nan       | 14    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 66    | 12           |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600051  | 1946-11-26 00:00:00 | HUS vs. WAS | L    | 24    | nan   | nan      | nan    | nan    | nan       | 20    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 68    | -10          |
| 21946       | 1610610036 | WAS                 | Washington Capitols               | 24600054  | 1946-11-27 00:00:00 | WAS vs. CHS | W    | 29    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 14   | 75    | 8            |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600055  | 1946-11-27 00:00:00 | PIT vs. CLR | W    | 20    | nan   | nan      | nan    | nan    | nan       | 22    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 22   | 62    | 2            |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600056  | 1946-11-27 00:00:00 | NYK vs. BOM | W    | 23    | nan   | nan      | nan    | nan    | nan       | 21    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 67    | 7            |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600057  | 1946-11-28 00:00:00 | CHS vs. BOM | L    | 26    | nan   | nan      | nan    | nan    | nan       | 20    | 22    | 0.909    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 72    | -3           |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600058  | 1946-11-28 00:00:00 | PRO vs. NYK | L    | 21    | nan   | nan      | nan    | nan    | nan       | 16    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 58    | -2           |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600059  | 1946-11-28 00:00:00 | BOS vs. PIT | W    | 22    | nan   | nan      | nan    | nan    | nan       | 15    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 59    | 4            |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600060  | 1946-11-28 00:00:00 | PHW vs. DEF | L    | 21    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 19   | 55    | -13          |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600061  | 1946-11-29 00:00:00 | HUS vs. CLR | L    | 27    | nan   | nan      | nan    | nan    | nan       | 18    | 25    | 0.72     | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 23   | 72    | -15          |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600064  | 1946-11-30 00:00:00 | BOM vs. DEF | W    | 23    | 95    | 0.242    | nan    | nan    | nan       | 14    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 60    | 3            |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600063  | 1946-11-30 00:00:00 | NYK vs. PHW | W    | 26    | nan   | nan      | nan    | nan    | nan       | 12    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 64    | 4            |
| 21946       | 1610610036 | WAS                 | Washington Capitols               | 24600065  | 1946-11-30 00:00:00 | WAS vs. PIT | W    | 16    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 49    | 9            |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600062  | 1946-11-30 00:00:00 | PRO vs. HUS | W    | 35    | nan   | nan      | nan    | nan    | nan       | 9     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 79    | 14           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600066  | 1946-12-01 00:00:00 | CHS vs. BOS | W    | 25    | nan   | nan      | nan    | nan    | nan       | 16    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 17   | 66    | 10           |
| 21946       | 1610610026 | CLR                 | Cleveland Rebels                  | 24600067  | 1946-12-01 00:00:00 | CLR vs. DEF | W    | 16    | nan   | nan      | nan    | nan    | nan       | 17    | 22    | 0.773    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 15   | 49    | 2            |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600068  | 1946-12-02 00:00:00 | PIT vs. BOS | L    | 17    | nan   | nan      | nan    | nan    | nan       | 10    | 17    | 0.588    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 44    | -2           |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600069  | 1946-12-03 00:00:00 | PHW vs. PRO | W    | 33    | nan   | nan      | nan    | nan    | nan       | 10    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 10   | 76    | 8            |
| 21946       | 1610610036 | WAS                 | Washington Capitols               | 24600070  | 1946-12-04 00:00:00 | WAS vs. PRO | W    | 34    | nan   | nan      | nan    | nan    | nan       | 12    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 16   | 80    | 18           |
| 21946       | 1610612752 | NYK                 | New York Knicks                   | 24600071  | 1946-12-04 00:00:00 | NYK vs. DEF | W    | 28    | nan   | nan      | nan    | nan    | nan       | 14    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 17   | 70    | 13           |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600072  | 1946-12-04 00:00:00 | PIT vs. CHS | L    | 16    | nan   | nan      | nan    | nan    | nan       | 14    | 24    | 0.583    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 46    | -11          |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600075  | 1946-12-05 00:00:00 | BOM vs. PIT | W    | 24    | 89    | 0.27     | nan    | nan    | nan       | 18    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 66    | 11           |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600074  | 1946-12-05 00:00:00 | BOS vs. DEF | L    | 24    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 61    | -4           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600073  | 1946-12-05 00:00:00 | CHS vs. HUS | L    | 23    | nan   | nan      | nan    | nan    | nan       | 15    | 22    | 0.682    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 28   | 61    | -4           |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600076  | 1946-12-05 00:00:00 | PHW vs. NYK | W    | 22    | nan   | nan      | nan    | nan    | nan       | 18    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 62    | 11           |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600077  | 1946-12-07 00:00:00 | CHS vs. CLR | W    | 38    | nan   | nan      | nan    | nan    | nan       | 18    | 28    | 0.643    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 24   | 86    | 8            |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600080  | 1946-12-07 00:00:00 | PRO vs. HUS | L    | 20    | nan   | nan...
```

In [ ]:
Output

WITH home_team_stats AS (
| season_id   | team_id    | team_abbreviation   | team_name                         | game_id   | game_date           | matchup     | wl   | fgm   | fga   | fg_pct   | fg3m   | fg3a   | fg3_pct   | ftm   | fta   | ft_pct   | oreb   | dreb   | reb   | ast   | stl   | blk   | tov   | pf   | pts   | plus_minus   |
|:------------|:-----------|:--------------------|:----------------------------------|:----------|:--------------------|:------------|:-----|:------|:------|:---------|:-------|:-------|:----------|:------|:------|:---------|:-------|:-------|:------|:------|:------|:------|:------|:-----|:------|:-------------|
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600001  | 1946-11-01 00:00:00 | HUS vs. NYK | L    | 25    | nan   | nan      | nan    | nan    | nan       | 16    | 29    | 0.552    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 66    | -2           |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600003  | 1946-11-02 00:00:00 | BOM vs. PIT | W    | 20    | 59    | 0.339    | nan    | nan    | nan       | 16    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 56    | 5            |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600002  | 1946-11-02 00:00:00 | PRO vs. BOS | W    | 21    | nan   | nan      | nan    | nan    | nan       | 17    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 59    | 6            |
| 21946       | 1610610025 | CHS                 | Chicago Stags                     | 24600004  | 1946-11-02 00:00:00 | CHS vs. NYK | W    | 21    | nan   | nan      | nan    | nan    | nan       | 21    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 63    | 16           |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600005  | 1946-11-02 00:00:00 | DEF vs. WAS | L    | 10    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 33    | -17          |
| 21946       | 1610610026 | CLR                 | Cleveland Rebels                  | 24600006  | 1946-11-03 00:00:00 | CLR vs. HUS | W    | 24    | nan   | nan      | nan    | nan    | nan       | 23    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 71    | 11           |
| 21946       | 1610610031 | PIT                 | Pittsburgh Ironmen                | 24600007  | 1946-11-04 00:00:00 | PIT vs. WAS | L    | 19    | nan   | nan      | nan    | nan    | nan       | 18    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 56    | -15          |
| 21946       | 1610612738 | BOS                 | Boston Celtics                    | 24600008  | 1946-11-05 00:00:00 | BOS vs. CHS | L    | 23    | nan   | nan      | nan    | nan    | nan       | 9     | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 55    | -2           |
| 21946       | 1610610028 | DEF                 | Detroit Falcons                   | 24600009  | 1946-11-05 00:00:00 | DEF vs. BOM | L    | 18    | nan   | nan      | nan    | nan    | nan       | 13    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | nan  | 49    | -4           |
| 21946       | 1610610032 | PRO                 | Providence Steamrollers           | 24600011  | 1946-11-07 00:00:00 | PRO vs. CHS | W    | 31    | nan   | nan      | nan    | nan    | nan       | 11    | nan   | nan      | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 20   | 73    | 8            |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers                 | 24600012  | 1946-11-07 00:00:00 | BOM vs. NYK | L    | 25    | 104   | 0.24     | nan    | nan    | nan       | 13    | 20    | 0.65     | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 63    | -5           |
| 21946       | 1610612744 | PHW                 | Philadelphia Warriors             | 24600010  | 1946-11-07 00:00:00 | PHW vs. PIT | W    | 28    | nan   | nan      | nan    | nan    | nan       | 25    | 39    | 0.641    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 24   | 81    | 6            |
| 21946       | 1610610035 | HUS                 | Toronto Huskies                   | 24600013  | 1946-11-08 00:00:00 | HUS vs. DEF | W    | 31    | nan   | nan      | nan    | nan    | nan       | 11    | 26    | 0.423    | nan    | nan    | nan   | nan   | nan   | nan   | nan   | 21   | 73    | 2            |
| 21946       | 1610610034 | BOM                 | St. Louis Bombers
```